Feature/component usage
jc-thumper/TF pull request #14
Opened 2021-06-16 04:12 UTC by tringuyen-novobi

2021-06-16 07:20 UTC, ryantran-novobi commented on tf_stock/wizard/component_usage_wizard.py
> +    _name = "component.usage.wizard"
`mrp.component.usage.report.wizard`

2021-06-16 07:21 UTC, ryantran-novobi commented on tf_stock/wizard/production_report_wizard.py
> +    _name = "production.wizard"
`mrp.production.report.wizard`

2021-06-21 17:13 UTC, ryantran-novobi requested changes

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/report/component_usage_report.py
> +            sml_ids = self.env['stock.move.line'].search([('product_id', 'in', products_ids)]).ids
```suggestion
            sml = self.env['stock.move.line'].search([('product_id', 'in', products.ids)])
```

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/report/component_usage_report.py
> +        return [('id', 'in', sml_ids)]
```suggestion
        return [('id', 'in', sml.ids)]
```

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/report/component_usage_report.py
> +        if operator == 'ilike':
what if `operator` is not `ilike`?

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/report/component_usage_report_views.xml
> +    <record model="ir.ui.view" id="component_usage_report">
change the `id` to match with the wizard, e.g `mrp_component_usage_report`

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/report/production_report_views.xml
> +    <record model="ir.ui.view" id="production_report">
change `id` and be more explicit

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/wizard/component_usage_wizard.py
> +    start_date = fields.Datetime(string='Start Date', default=fields.Datetime.now())
If in this line, the default is the starting time of the date, I would be very happy. Sadly, setting 2 default time with the same amount seems redundant. I rather leave this field without any default.

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/wizard/component_usage_wizard.py
> +    def _onchange_start_end_date(self):
It's good to be careful, but it should be checked when we get the report, rather than every time these values are changed.

This block should be after the below `self.ensure_one()`

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/wizard/component_usage_wizard.py
> +        domain = [('date', '<=', self.end_date), ('date', '>=', self.start_date), ('reference', 'ilike', 'WH/MO')]
We still settle with using the reference like `WH/MO` ?

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/wizard/component_usage_wizard.py
> +        domain += [('location_dest_id', '=', production_location.id)]
why not search first, then do one-off domain, rather than splitting like this?

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/wizard/component_usage_wizard.py
> +        domain += [('location_dest_id', '=', production_location.id)]
what if `production_location` ends up as a recordset? Will this domain still work?

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/wizard/component_usage_wizard.py
> +            'name': _('Component Usage Report ({} - {})').format(self.start_date, self.end_date),
```suggestion
            'name': _('Component Usage Report (%s - %s)') % (self.start_date, self.end_date),
```

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/wizard/component_usage_wizard_views.xml
> +                    <field name="start_date"/>
```suggestion
                    <field name="start_date" required="1" />
```

2021-06-21 17:13 UTC, ryantran-novobi commented on tf_stock/wizard/component_usage_wizard_views.xml
> +                    <field name="end_date"/>
```suggestion
                    <field name="end_date" required="1" />
```

2021-06-22 03:31 UTC, ryantran-novobi commented on tf_stock/wizard/component_usage_wizard.py
> +        domain += [('location_dest_id', '=', production_location.id)]
@tringuyen-novobi

2021-06-22 03:32 UTC, ryantran-novobi commented
It's looking good after the new commit, but I think we should also take care of the domain for production location

2021-06-22 03:36 UTC, tringuyen-novobi commented on tf_stock/wizard/component_usage_wizard.py
> +        domain += [('location_dest_id', '=', production_location.id)]
c.Hoa need to discuss for the condition, please wait after the afternoon meeting

2021-06-22 03:58 UTC, ryantran-novobi commented
@tringuyen-novobi there are conflicts for this PR

2021-06-22 04:06 UTC, merged